from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterator


PRETRAINING_RECIPES = {
    "fineweb_edu": {
        "hf_repo": "HuggingFaceFW/fineweb-edu",
        "subset": "sample-10BT",
        "text_field": "text",
        "description": "High-quality educational web content filtered by fine-grained classifiers.",
        "license": "ODC-By 1.0",
        "default_weight": 0.35,
    },
    "cosmopedia": {
        "hf_repo": "HuggingFaceTB/cosmopedia",
        "subset": "auto_math_text",
        "text_field": "text",
        "description": "Synthetic educational textbooks, courses, and stories generated by Mixtral.",
        "license": "Apache 2.0",
        "default_weight": 0.25,
    },
    "finemath": {
        "hf_repo": "HuggingFaceFW/finemath",
        "subset": "finemath-4plus",
        "text_field": "text",
        "description": "High quality mathematical reasoning and step-by-step problem solving.",
        "license": "ODC-By 1.0",
        "default_weight": 0.15,
    },
    "the_stack": {
        "hf_repo": "bigcode/the-stack-smol-xl",
        "subset": "data",
        "text_field": "content",
        "description": "Clean, permissively-licensed programming and algorithm code.",
        "license": "Permissive (MIT/Apache/BSD)",
        "default_weight": 0.15,
    },
    "dolma_sample": {
        "hf_repo": "allenai/dolma",
        "subset": "v1_6-sample",
        "text_field": "text",
        "description": "Broad, diverse open pretraining text curated by AI2.",
        "license": "Open Data Commons",
        "default_weight": 0.10,
    },
}


class PretrainingDatasetIngester:
    """Streams and stages premier open pretraining datasets (FineWeb-Edu, Cosmopedia, FineMath, The Stack)."""

    def __init__(self, raw_dir: str | Path = "data/raw") -> None:
        self.raw_dir = Path(raw_dir)
        self.raw_dir.mkdir(parents=True, exist_ok=True)

    def stream_dataset(
        self,
        dataset_key: str,
        num_documents: int = 5000,
        output_file: str | Path | None = None,
    ) -> Path:
        """Streams documents from Hugging Face datasets into local JSONL for VEYRA training."""
        if dataset_key not in PRETRAINING_RECIPES:
            raise ValueError(
                f"Unknown dataset '{dataset_key}'. Choose from: {list(PRETRAINING_RECIPES.keys())}"
            )

        recipe = PRETRAINING_RECIPES[dataset_key]
        target_path = Path(output_file) if output_file else self.raw_dir / f"{dataset_key}.jsonl"

        print(f"\n--> Ingesting {recipe['hf_repo']} ({recipe['description']})...")
        print(f"    Target docs: {num_documents:,} | Output: {target_path}")

        try:
            from datasets import load_dataset
        except ImportError:
            raise ImportError(
                "The 'datasets' package is required to stream pretraining datasets. "
                "Install it with: pip install datasets"
            )

        # Stream without downloading the entire multi-terabyte corpus
        ds = load_dataset(
            recipe["hf_repo"],
            name=recipe["subset"],
            split="train",
            streaming=True,
        )

        text_col = recipe["text_field"]
        collected = 0

        with open(target_path, "w", encoding="utf-8") as out:
            for item in ds:
                text = item.get(text_col, "")
                if not text or len(text.strip()) < 50:
                    continue

                record = {
                    "text": text,
                    "source": dataset_key,
                    "license": recipe["license"],
                }
                out.write(json.dumps(record, ensure_ascii=False) + "\n")
                collected += 1

                if collected % 500 == 0:
                    print(f"    Streamed {collected:,}/{num_documents:,} documents...", end="\r", flush=True)

                if collected >= num_documents:
                    break

        print(f"\n    Completed! Saved {collected:,} clean documents to {target_path.resolve()}")
        return target_path

    def build_veyra_curated_recipe(
        self,
        total_docs: int = 15000,
        output_dir: str | Path | None = None,
    ) -> list[Path]:
        """Ingests the full balanced VEYRA pretraining mix across web, textbooks, math, and code."""
        out_dir = Path(output_dir) if output_dir else self.raw_dir
        saved_paths: list[Path] = []

        print("\n" + "=" * 70)
        print("  BUILDING VEYRA PRETRAINING DATASET RECIPE")
        print("  Sources: FineWeb-Edu + Cosmopedia + FineMath + The Stack + Dolma")
        print("=" * 70)

        for key, recipe in PRETRAINING_RECIPES.items():
            count = int(total_docs * recipe["default_weight"])
            dest = out_dir / f"{key}.jsonl"
            try:
                p = self.stream_dataset(key, num_documents=count, output_file=dest)
                saved_paths.append(p)
            except Exception as e:
                print(f"  [WARN] Could not fetch {key}: {e}. Skipping...")

        return saved_paths
